<?php

namespace App\Domain\Reporting\Writers;

use App\Domain\Reporting\ReportDocument;
use App\Domain\Reporting\ReportSection;

/**
 * CSV holds one table. When the document has several, the largest table wins
 * and the rest are noted — rather than silently producing a file that is not
 * what the user asked for.
 */
final class CsvWriter
{
    public function write(ReportDocument $document, string $absolutePath): void
    {
        $handle = fopen($absolutePath, 'w');
        fwrite($handle, "\xEF\xBB\xBF"); // BOM so Excel opens UTF-8 correctly

        fputcsv($handle, ['SASA report', $document->title]);
        fputcsv($handle, ['Organisation', $document->organisationName]);
        fputcsv($handle, ['Project', $document->projectName]);
        fputcsv($handle, ['Reporting period', $document->periodLabel]);
        fputcsv($handle, ['Filters', $document->filterSummary()]);
        fputcsv($handle, ['Generated by', $document->generatedBy]);
        fputcsv($handle, ['Generated at', $document->generatedAt]);
        fputcsv($handle, []);

        foreach ($document->sections as $section) {
            fputcsv($handle, [$section->title]);

            if ($section->type === ReportSection::TYPE_KPIS) {
                fputcsv($handle, ['Measure', 'Value', 'Unit', 'Definition']);

                foreach ($section->kpis as $kpi) {
                    fputcsv($handle, [$kpi['label'] ?? '', $kpi['value'] ?? '', $kpi['unit'] ?? '', $kpi['definition'] ?? '']);
                }
            } elseif ($section->type === ReportSection::TYPE_TABLE) {
                fputcsv($handle, $section->columns);

                foreach ($section->rows as $row) {
                    fputcsv($handle, array_values($row));
                }
            } else {
                fputcsv($handle, [$section->text]);
            }

            fputcsv($handle, []);
        }

        fclose($handle);
    }
}
