<?php

namespace App\Domain\Reporting\Writers;

use App\Domain\Reporting\ReportDocument;
use App\Domain\Reporting\ReportSection;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

/** Raw data plus a cover sheet carrying the parameters and definitions. */
final class ExcelWriter
{
    public function write(ReportDocument $document, string $absolutePath): void
    {
        $spreadsheet = new Spreadsheet;
        $spreadsheet->getProperties()
            ->setCreator('SASA')
            ->setTitle($document->title)
            ->setSubject($document->projectName)
            ->setDescription('Generated from live SASA data on '.$document->generatedAt);

        $cover = $spreadsheet->getActiveSheet();
        $cover->setTitle('About this report');
        $this->writeCover($cover, $document);

        foreach ($document->sections as $index => $section) {
            $sheet = $spreadsheet->createSheet();
            $sheet->setTitle($this->sheetName($section->title, $index));

            if ($section->type === ReportSection::TYPE_KPIS) {
                $this->writeKpiSheet($sheet, $section);
            } elseif ($section->type === ReportSection::TYPE_TABLE) {
                $this->writeTableSheet($sheet, $section);
            } else {
                $sheet->setCellValue('A1', $section->title);
                $sheet->setCellValue('A3', $section->text ?? '');
                $sheet->getStyle('A3')->getAlignment()->setWrapText(true);
            }
        }

        $spreadsheet->setActiveSheetIndex(0);
        (new Xlsx($spreadsheet))->save($absolutePath);
        $spreadsheet->disconnectWorksheets();
    }

    private function writeCover($sheet, ReportDocument $document): void
    {
        $rows = [
            ['SASA — Stakeholder Intelligence & Voice', ''],
            ['Report', $document->title],
            ['Organisation', $document->organisationName],
            ['Project', $document->projectName],
            ['Reporting period', $document->periodLabel],
            ['Filters', $document->filterSummary()],
            ['Generated by', $document->generatedBy],
            ['Generated at', $document->generatedAt],
            ['', ''],
            ['Definitions', 'Every number in this report has one definition.'],
        ];

        foreach ($rows as $index => [$label, $value]) {
            $sheet->setCellValue('A'.($index + 1), $label);
            $sheet->setCellValue('B'.($index + 1), $value);
        }

        $row = count($rows) + 1;

        foreach ($document->definitions() as $label => $definition) {
            $sheet->setCellValue('A'.$row, $label);
            $sheet->setCellValue('B'.$row, $definition);
            $sheet->getStyle('B'.$row)->getAlignment()->setWrapText(true);
            $row++;
        }

        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
        $sheet->getStyle('A1:A'.$row)->getFont()->setBold(true);
        $sheet->getColumnDimension('A')->setWidth(28);
        $sheet->getColumnDimension('B')->setWidth(90);
    }

    private function writeKpiSheet($sheet, ReportSection $section): void
    {
        $sheet->fromArray(['Measure', 'Value', 'Unit', 'Definition'], null, 'A1');
        $row = 2;

        foreach ($section->kpis as $kpi) {
            $sheet->fromArray([
                $kpi['label'] ?? '',
                $kpi['value'] ?? '',
                $kpi['unit'] ?? '',
                $kpi['definition'] ?? '',
            ], null, 'A'.$row);
            $sheet->getStyle('D'.$row)->getAlignment()->setWrapText(true);
            $row++;
        }

        $this->styleHeader($sheet, 'A1:D1');
        foreach (['A' => 40, 'B' => 14, 'C' => 12, 'D' => 90] as $column => $width) {
            $sheet->getColumnDimension($column)->setWidth($width);
        }
    }

    private function writeTableSheet($sheet, ReportSection $section): void
    {
        if ($section->columns === []) {
            return;
        }

        $sheet->fromArray($section->columns, null, 'A1');

        $row = 2;
        foreach ($section->rows as $dataRow) {
            $sheet->fromArray(array_values($dataRow), null, 'A'.$row);
            $row++;
        }

        $lastColumn = chr(ord('A') + max(0, count($section->columns) - 1));
        $this->styleHeader($sheet, 'A1:'.$lastColumn.'1');
        $sheet->setAutoFilter('A1:'.$lastColumn.max(1, $row - 1));
        $sheet->freezePane('A2');

        foreach (range('A', $lastColumn) as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(true);
        }
    }

    private function styleHeader($sheet, string $range): void
    {
        $sheet->getStyle($range)->getFont()->setBold(true)->getColor()->setARGB('FFFFFFFF');
        $sheet->getStyle($range)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FF0F3D46');
        $sheet->getStyle($range)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        $sheet->getRowDimension(1)->setRowHeight(22);
    }

    private function sheetName(string $title, int $index): string
    {
        $clean = preg_replace('/[\\\\\\/\\?\\*\\[\\]:]/', '', $title);

        return mb_substr($clean ?: 'Sheet '.($index + 1), 0, 28).' '.($index + 1);
    }
}
