<?php

namespace App\Domain\Reporting\Writers;

use App\Domain\Reporting\ReportDocument;
use App\Domain\Reporting\ReportSection;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\Shared\Converter;
use PhpOffice\PhpWord\SimpleType\Jc;
use PhpOffice\PhpWord\Style\Language;

/** An editable narrative document with the tables placed. */
final class WordWriter
{
    private const INK = '111827';

    private const BRAND = '0F3D46';

    private const MUTED = '6B7280';

    public function write(ReportDocument $document, string $absolutePath): void
    {
        $word = new PhpWord;
        $word->getSettings()->setThemeFontLang(new Language(Language::EN_GB));

        $word->setDefaultFontName('Calibri');
        $word->setDefaultFontSize(10);

        $word->addTitleStyle(1, ['size' => 20, 'bold' => true, 'color' => self::BRAND], ['spaceAfter' => 160]);
        $word->addTitleStyle(2, ['size' => 13, 'bold' => true, 'color' => self::INK], ['spaceBefore' => 320, 'spaceAfter' => 120]);

        $section = $word->addSection([
            'marginTop' => Converter::cmToTwip(2),
            'marginBottom' => Converter::cmToTwip(2),
            'marginLeft' => Converter::cmToTwip(2),
            'marginRight' => Converter::cmToTwip(2),
        ]);

        $section->addText('SASA · Stakeholder Intelligence & Voice', ['size' => 9, 'bold' => true, 'color' => self::MUTED]);
        $section->addTitle($document->title, 1);
        $section->addText($document->projectName.' · '.$document->organisationName, ['size' => 11, 'color' => self::INK]);
        $section->addText('Reporting period: '.$document->periodLabel, ['size' => 10, 'color' => self::MUTED]);
        $section->addText($document->filterSummary(), ['size' => 9, 'color' => self::MUTED]);
        $section->addText(
            'Generated by '.$document->generatedBy.' on '.$document->generatedAt.' from live SASA records.',
            ['size' => 9, 'italic' => true, 'color' => self::MUTED]
        );
        $section->addTextBreak(1);

        foreach ($document->sections as $reportSection) {
            $section->addTitle($reportSection->title, 2);

            if ($reportSection->description) {
                $section->addText($reportSection->description, ['size' => 9, 'italic' => true, 'color' => self::MUTED]);
                $section->addTextBreak(1);
            }

            match ($reportSection->type) {
                ReportSection::TYPE_KPIS => $this->writeKpis($section, $reportSection),
                ReportSection::TYPE_TABLE => $this->writeTable($section, $reportSection),
                default => $section->addText((string) $reportSection->text),
            };
        }

        $this->writeDefinitions($section, $document);

        $word->save($absolutePath, 'Word2007');
    }

    private function writeKpis($section, ReportSection $reportSection): void
    {
        $table = $section->addTable($this->tableStyle());
        $table->addRow(null, ['tblHeader' => true]);
        foreach (['Measure', 'Value'] as $heading) {
            $this->headerCell($table, $heading, $heading === 'Measure' ? 7000 : 2400);
        }

        foreach ($reportSection->kpis as $kpi) {
            $table->addRow();
            $table->addCell(7000, ['valign' => 'center'])->addText((string) ($kpi['label'] ?? ''), ['size' => 10]);
            $table->addCell(2400, ['valign' => 'center'])->addText(
                $this->formatValue($kpi),
                ['size' => 11, 'bold' => true],
                ['alignment' => Jc::END]
            );
        }
    }

    private function writeTable($section, ReportSection $reportSection): void
    {
        if ($reportSection->columns === []) {
            return;
        }

        $width = (int) floor(9400 / max(1, count($reportSection->columns)));
        $table = $section->addTable($this->tableStyle());

        $table->addRow(null, ['tblHeader' => true]);
        foreach ($reportSection->columns as $column) {
            $this->headerCell($table, (string) $column, $width);
        }

        foreach ($reportSection->rows as $row) {
            $table->addRow();

            foreach (array_values($row) as $cell) {
                $table->addCell($width, ['valign' => 'top'])
                    ->addText(htmlspecialchars((string) $cell, ENT_QUOTES), ['size' => 9]);
            }
        }
    }

    private function writeDefinitions($section, ReportDocument $document): void
    {
        $definitions = $document->definitions();

        if ($definitions === []) {
            return;
        }

        $section->addTitle('How these numbers are defined', 2);

        foreach ($definitions as $label => $definition) {
            $section->addText($label, ['size' => 9, 'bold' => true]);
            $section->addText($definition, ['size' => 9, 'color' => self::MUTED], ['spaceAfter' => 100]);
        }
    }

    private function headerCell($table, string $text, int $width): void
    {
        $table->addCell($width, ['bgColor' => self::BRAND, 'valign' => 'center'])
            ->addText($text, ['bold' => true, 'color' => 'FFFFFF', 'size' => 9]);
    }

    private function tableStyle(): array
    {
        return [
            'borderSize' => 1,
            'borderColor' => 'D8DEE4',
            'cellMargin' => 70,
            'width' => 100 * 50,
            'unit' => 'pct',
        ];
    }

    private function formatValue(array $kpi): string
    {
        $value = $kpi['value'] ?? null;

        if ($value === null) {
            return 'No data';
        }

        return match ($kpi['unit'] ?? 'count') {
            'percent' => $value.'%',
            'days' => $value.' days',
            'hours' => $value.' hours',
            default => (string) $value,
        };
    }
}
