<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{ $document->title }}</title>
<style>
    @page { margin: 24mm 16mm 22mm 16mm; }
    * { box-sizing: border-box; }
    body {
        font-family: "DejaVu Sans", sans-serif;
        font-size: 9.5pt;
        color: #16232b;
        line-height: 1.5;
        margin: 0;
    }
    .cover-rule { height: 4px; background: #0f3d46; margin-bottom: 18px; }
    .eyebrow { font-size: 7.5pt; letter-spacing: 1.4px; text-transform: uppercase; color: #6b7f86; margin-bottom: 6px; }
    h1 { font-size: 21pt; margin: 0 0 4px; color: #0f3d46; letter-spacing: -0.3px; }
    .subtitle { font-size: 11pt; color: #16232b; margin-bottom: 14px; }
    .meta { width: 100%; border-collapse: collapse; margin-bottom: 22px; }
    .meta td { padding: 4px 0; vertical-align: top; font-size: 8.5pt; }
    .meta td.label { width: 130px; color: #6b7f86; text-transform: uppercase; letter-spacing: 0.6px; font-size: 7.5pt; padding-top: 6px; }
    h2 { font-size: 12.5pt; color: #0f3d46; margin: 26px 0 4px; padding-bottom: 6px; border-bottom: 1px solid #dbe3e6; }
    .section-note { font-size: 8pt; color: #6b7f86; margin: 0 0 10px; font-style: italic; }
    table.data { width: 100%; border-collapse: collapse; margin-bottom: 6px; }
    table.data th {
        background: #0f3d46; color: #fff; font-size: 7.5pt; text-align: left;
        padding: 7px 8px; font-weight: 600; letter-spacing: 0.3px;
    }
    table.data td { padding: 6px 8px; border-bottom: 1px solid #e6ecee; font-size: 8.5pt; vertical-align: top; }
    table.data tr:nth-child(even) td { background: #f7f9fa; }
    .kpi-grid { width: 100%; border-collapse: separate; border-spacing: 8px 8px; }
    .kpi {
        border: 1px solid #dbe3e6; border-left: 3px solid #0f3d46;
        padding: 10px 12px; width: 33%; background: #fbfcfc;
    }
    .kpi .label { font-size: 7.5pt; color: #6b7f86; text-transform: uppercase; letter-spacing: 0.6px; }
    .kpi .value { font-size: 17pt; color: #0f3d46; font-weight: bold; line-height: 1.2; }
    .kpi .context { font-size: 7pt; color: #6b7f86; }
    .definitions { margin-top: 28px; padding-top: 12px; border-top: 1px solid #dbe3e6; }
    .definitions dt { font-size: 8pt; font-weight: bold; margin-top: 8px; }
    .definitions dd { font-size: 8pt; color: #55666e; margin: 2px 0 0; }
    .footer { position: fixed; bottom: -14mm; left: 0; right: 0; font-size: 7pt; color: #8a9aa1; border-top: 1px solid #e6ecee; padding-top: 5px; }
    .empty { font-size: 8.5pt; color: #6b7f86; font-style: italic; padding: 10px 0; }
</style>
</head>
<body>

<div class="footer">
    {{ $document->title }} · {{ $document->projectName }} · Generated {{ $document->generatedAt }} from live SASA records.
</div>

<div class="cover-rule"></div>
<div class="eyebrow">SASA · Stakeholder Intelligence &amp; Voice</div>
<h1>{{ $document->title }}</h1>
<div class="subtitle">{{ $document->projectName }}</div>

<table class="meta">
    <tr><td class="label">Organisation</td><td>{{ $document->organisationName }}</td></tr>
    <tr><td class="label">Reporting period</td><td>{{ $document->periodLabel }}</td></tr>
    <tr><td class="label">Filters</td><td>{{ $document->filterSummary() }}</td></tr>
    <tr><td class="label">Generated by</td><td>{{ $document->generatedBy }}</td></tr>
    <tr><td class="label">Generated at</td><td>{{ $document->generatedAt }}</td></tr>
</table>

@foreach ($document->sections as $section)
    <h2>{{ $section->title }}</h2>
    @if ($section->description)
        <p class="section-note">{{ $section->description }}</p>
    @endif

    @if ($section->type === 'kpis')
        <table class="kpi-grid">
            @foreach (array_chunk($section->kpis, 3) as $row)
                <tr>
                    @foreach ($row as $kpi)
                        <td class="kpi">
                            <div class="label">{{ $kpi['label'] ?? '' }}</div>
                            <div class="value">
                                @php $value = $kpi['value'] ?? null; @endphp
                                @if ($value === null)
                                    —
                                @elseif (($kpi['unit'] ?? '') === 'percent')
                                    {{ $value }}%
                                @elseif (($kpi['unit'] ?? '') === 'days')
                                    {{ $value }}<span style="font-size:9pt"> days</span>
                                @elseif (($kpi['unit'] ?? '') === 'hours')
                                    {{ $value }}<span style="font-size:9pt"> hrs</span>
                                @else
                                    {{ number_format((float) $value) }}
                                @endif
                            </div>
                            @if (! empty($kpi['context']))
                                <div class="context">
                                    @foreach ($kpi['context'] as $key => $contextValue)
                                        {{ str_replace('_', ' ', $key) }}: {{ $contextValue }}@if(! $loop->last) · @endif
                                    @endforeach
                                </div>
                            @endif
                        </td>
                    @endforeach
                    @for ($i = count($row); $i < 3; $i++)<td></td>@endfor
                </tr>
            @endforeach
        </table>
    @elseif ($section->type === 'table')
        @if (count($section->rows) === 0)
            <p class="empty">No records matched these filters for this period.</p>
        @else
            <table class="data">
                <thead>
                    <tr>@foreach ($section->columns as $column)<th>{{ $column }}</th>@endforeach</tr>
                </thead>
                <tbody>
                @foreach ($section->rows as $row)
                    <tr>@foreach (array_values($row) as $cell)<td>{{ $cell }}</td>@endforeach</tr>
                @endforeach
                </tbody>
            </table>
        @endif
    @else
        <p>{{ $section->text }}</p>
    @endif
@endforeach

@if (count($document->definitions()) > 0)
    <div class="definitions">
        <h2 style="border:none; margin-bottom:2px;">How these numbers are defined</h2>
        <p class="section-note">Every number in SASA has one definition, so two reports never disagree.</p>
        <dl>
            @foreach ($document->definitions() as $label => $definition)
                <dt>{{ $label }}</dt>
                <dd>{{ $definition }}</dd>
            @endforeach
        </dl>
    </div>
@endif

</body>
</html>
